// This is a mock list of locations. No API was found for this list.
const mockLocations = [
   "Crawford House",
   "East House",
   "Hank Ingram House",
   "Gillette House",
   "Memorial House",
   "Murray House",
   "North House",
   "Stambaugh House",
   "Sutherland House",
   "West House",
   "Warren College",
   "Moore College",
   "Mayfields",
   "McGills",
   "McTyeire",
   "Barnard Hall",
   "Cole Hall",
   "Lupton House",
   "Scales House",
   "Stapleton House",
   "Tolman Hall",
   "Vanderbilt Hall",
   "Vaughn House",
   "Blakemore House",
   "Chaffins",
   "Lewis",
   "Morgan",
   "Carmichael College",
   "Stevenson Library",
   "MRB",
   "FGH",
   "Buttrick",
   "Sony Building",
   "Divinity School",
   "Rand",
   "Wilson",
   "Kirkland",
   "EBI",
   "Olin",
   "The Wondry",
   "Blair",
   "Central Library",
   "Peabody Library",
   "Commons Center",
   "The Rec",
   "The Pub",
   "Alumni Hall",
   "Kissam",
   "Rothschild",
   "Zeppos",
];

export const fetchSuggestedLocations = (input) => {
   // Filter locations based on input
   return mockLocations.filter((location) =>
      location.toLowerCase().includes(input.toLowerCase())
   );
};
